
language: python # => 1

python: # => 2

  - "2.7"

services: # => 3

  - mysql

env: # => 4

  -DJANGO=1.11 DB=mysql
install: # => 


  - pip install -r requirements.txt

before_script: # => 6

  - mysql -e 'create database test;' -u root


  - python manage.py test
